/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package micro.apps.cli

class CliApp {
    val greeting: String
        get() {
            return "Hello World"
        }
}

fun main(args: Array<String>) {
    println(CliApp().greeting)
}
