version: '3'

services:

  mongodb:
    image: bitnami/mongodb:latest
    ports:
      - '27017:27017'
    environment:
      MONGODB_ROOT_PASSWORD: password321
      MONGODB_DATABASE: guestbook
      MONGODB_USERNAME: mdbuser
      MONGODB_PASSWORD: password123
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: replicaset01
    volumes:
      - mongodb_primary_data:/bitnami
#      - ./deploy/mongodb/init.js:/init.js

  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.0
    ports:
      - 2181:2181
    volumes:
      - zookeeper:/var/lib/zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  broker:
    image: confluentinc/cp-kafka:5.0.0
    ports:
      - 9092:9092
    volumes:
      - kafka:/var/lib/kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      CONFLUENT_METRICS_ENABLE: 'false'
    links:
      - zookeeper

  schema-registry:
    image: confluentinc/cp-schema-registry:5.0.0
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      BOOTSTRAP_SERVERS: PLAINTEXT://broker:9092
    links:
      - zookeeper
      - broker

  rest-proxy:
    image: confluentinc/cp-kafka-rest:5.0.0
    ports:
      - 8082:8082
    environment:
      BOOTSTRAP_SERVERS: broker:9092
      KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      KAFKA_REST_HOST_NAME: rest-proxy
    links:
      - zookeeper
      - broker
      - schema-registry

  guestbook-api:
    image: xmlking/micro-apps-guestbook-api:1.0.0-SNAPSHOT
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_USERNAME: admin
      MONGO_PASSWORD: admin
      MONGO_AUTHENTICATION_DATABASE: admin
    links:
      - mongodb
    depends_on:
      - mongodb

  stream-api:
    image: xmlking/micro-apps-stream-api:1.0.0-SNAPSHOT
    environment:
      SPRING_PROFILES_ACTIVE: docker

  guestbook-app:
    image: xmlking/micro-apps-guestbook-app:1.0.0-SNAPSHOT
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: docker
      GUESTBOOK_API_URL: http://guestbook-api:8080
      STREAM_API_URL: http://stream-api:8080
    links:
      - guestbook-api
      - stream-api
    depends_on:
      - guestbook-api
      - stream-api

volumes:
  mongodb_primary_data:
  zookeeper:
  kafka:
