---
micronaut:
    application:
        name: guestbook-service
                
#Uncomment to set server port
#    server:
#        port: 8080

---
mongodb:
    uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}"
---
micronaut:
    metrics:
        enabled: true
        export:
            prometheus:
                enabled: true
                step: PT1M
                descriptions: true
---
tracing:
  jaeger:
    enabled: true
    sampler:
      probability: 0.1

---
kafka:
    bootstrap:
        servers: localhost:9092
